### ISSUE TITLE
Referenced package.xml seems to be copied 1:1

### ISSUE THREAD

**Issue by abjerner** [tomfulton/grunt-umbraco-package#7]
Hi Tom,

Great initiative creating this package :D

I'm not sure whether I have done something wrong, but I've tried following the instructions from the readme file.

My main problem is that when referencing my package.xml file, it seems to be copied 1:1 to the ZIP file, and the `<files />` element in the XML remains empty, even though the files of my package are added to the ZIP file. Values like the name and version specified in the Grunt config aren't added to the manifest either.

I also experience a few other issues:

- If I run the task again, the ZIP file isn't overwritten, so if I run the task twice, files from my package will be added twice to the ZIP file.

- Running the task will create a new temporary folder in the source directory. I guess this is fine, but the temporary folder isn't deleted afterwards.

Since I couldn't get this to work, I've created a new Grunt task roughly based on this one. Should I create a pull request with my changes, or just create a new, similar package?

My task will take the same configuration as yours - except the `manifest` option - and then automatically generate the entire manifest. This however doesn't take extra resources like document types, templates and similar into consideration, but that could be added as well.

**Comment by tomfulton** [comment]
Hi, thanks for reporting!

For the issue with the `<files />` element, the usage is a bit strange, you need to hardcode the list of files currently.  In Archetype we do this using [grunt templates](https://github.com/tomfulton/grunt-umbraco-package/blob/master/tasks/umbraco_package.js#L60) and [some logic](https://github.com/imulus/Archetype/blob/master/config/package.xml#L31-L37) in the `package.xml` file to generate the list automatically.  I believe it was done this way due to lack of xml parsing node packages at the time (that didn't require python).  

Anyway, I'd gladly accept your pull request to generate the manifest automatically, that sounds much more ideal.  Do you think there is any value in keeping the current behavior and making the "automatic" manifest optional, or should we just get rid of it altogether and define everything in the config?

I also agree with your other comments, both should be easy fixes...if you have time for a pull request I'll gladly take a look :smile:

**Comment by abjerner** [comment]
I suppose specifying the path to the manifest can be made optional. If specified, it will just copy the manifest. If not specified, the manifest will automatically be generated by the package.

I'll look into implementing that, and then make a pull request ;)

**Comment by abjerner** [comment]
Closing the issue here since I've now created a pull request: #8.
